services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    hostname: portainer
    networks:
      - default-network
    ports:
      - "29002:9000"
      - "28000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/portainer/data

networks:
  default-network:
    driver: bridge
